#
# Jz4760 Platform Support
#
snd-soc-jz4760-objs := jz4760-pcm.o
snd-soc-jz4760-ac97-objs := jz4760-ac97.o
snd-soc-jz4760-i2s-objs := jz4760-i2s.o

obj-$(CONFIG_SND_JZ4760_SOC) += snd-soc-jz4760.o
obj-$(CONFIG_SND_JZ4760_SOC_AC97) += snd-soc-jz4760-ac97.o
obj-$(CONFIG_SND_JZ4760_SOC_I2S) += snd-soc-jz4760-i2s.o

# Jz4760 Machine Support
snd-soc-lepus-objs := lepus.o

obj-$(CONFIG_SND_JZ4760_SOC_LEPUS) += snd-soc-lepus.o
