#
# Jz4760 Platform Support
#
snd-soc-jz4770-objs := jz4770-pcm.o
snd-soc-jz4770-i2s-objs := jz4770-i2s.o

obj-$(CONFIG_SND_JZ4770_SOC) += snd-soc-jz4770.o
obj-$(CONFIG_SND_JZ4770_SOC_I2S) += snd-soc-jz4770-i2s.o

# Jz4760 Machine Support
snd-soc-pisces-icdc-objs := pisces_icdc.o

obj-$(CONFIG_SND_JZ4770_SOC_PISCES_ICDC) += snd-soc-pisces-icdc.o
